# Site settings
title: Xiran Ou's Bizarre Adventures
name: Xiran Ou
email: xiranou@gmail.com
description: My unexpected journey into a world of codes
# baseurl: "/xiranou.github.io"
url: "http://xiranou.github.io"
github_username:  xiranou

# Build settings
# kramdown:
#   use_coderay: true
# highlighter: rouge