# Site settings
title: \@riceynoodle
name: Xiran Ou
email: xiranou@gmail.com
description: Xiran Ou's Bizarre Adventures
baseurl: "/xiranou.github.io"
url: "http://xiranou.github.io"
twitter_username: \@riceynoodle
github_username:  xiranou

# Build settings
highlighter: rouge
encoding: utf-8