# Site settings
title: Xiran Ou's Bizarre Adventures
name: Xiran Ou
email: xiranou@gmail.com
description: My unexpected journey into a world of codes
baseurl: ""
url: "http://xiranou.github.io"
twitter_username: riceynoodle
github_username:  xiranou

# Build settings
markdown: kramdown